name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

permissions:
  contents: read

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and validate extension
        uses: natapol2547/blender-extension-builder@main
        with:
          source-dir: '.'
          create-release: 'false'
